language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
node_js:
  - "4"
  - "5"
  - "6"
install:
  - npm install
script:
  - npm test
