language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "4.0"
  - "4.1"
  - "5.0"
  - "5.1"
install:
  - CXX="g++-4.8" npm install
script:
  - npm test
