app:
  title: PCIC Climate Explorer

help:

science:
  title: '# Scientific References'
  content: |
    ## Statistically Downscaled Climate Scenarios

    **Bürger, G.**,** T.Q. Murdock**, **A.T. Werner**, **S.R. Sobie**, and **A.J. Cannon**, 2012: [Downscaling extremes - an intercomparison of multiple statistical methods for present climate](http://journals.ametsoc.org/doi/abs/10.1175/JCLI-D-11-00408.1). _Journal of Climate_, **25**, 4366–4388. doi:10.1175/JCLI-D-11-00408.1.

    **Bürger, G.**, **S.R. Sobie**, **A.J. Cannon**, **A.T. Werner**, and **T.Q. Murdock**, 2013: [Downscaling extremes - an intercomparison of multiple methods for future climate](http://journals.ametsoc.org/doi/abs/10.1175/JCLI-D-12-00249.1)._ Journal of Climate_, **26**, 3429-3449. doi:10.1175/JCLI-D-12-00249.1.

    **Cannon, A.J.**, 2015: Selecting GCM scenarios that span the range of changes in a multimodel ensemble: application to CMIP5 climate extremes indices._ Journal of Climate_, **28**(3): 1260-1267. doi:10.1175/JCLI-D-14-00636.1

    **Cannon, A.J.**,** S.R. Sobie**, and **T.Q. Murdock**, 2015: [Precipitation by Quantile Mapping: How Well Do Methods Preserve Changes in Quantiles and Extremes?](https://journals.ametsoc.org/doi/abs/10.1175/JCLI-D-14-00754.1) _Journal of Climate_, **28**(17), 6938-6959, doi:10.1175/JCLI-D-14-00754.1.

    Giorgi, F. and Francisco, R., 2000: Evaluating uncertainties in the prediction of regional climate change. _Geophysical Research Letters_, **27**(9), 1295-1298.

    Gudmundsson, L., J. B. Bremnes, J. E. Haugen, and T. Engen-Skaugen, 2012: [Technical Note: Downscaling RCM precipitation to the station scale using statistical transformations - a comparison of methods](http://www.hydrol-earth-syst-sci.net/16/3383/2012/hess-16-3383-2012.html). _Hydrology and Earth System Sciences_, **16**, 3383–3390, doi:10.5194/hess-16-3383-2012.

    **Hiebert, J.**, **A. Cannon**, **A. Schoeneberg**,** S. Sobie**, and **T. Murdock**, 2018: [ClimDown: Climate Downscaling in R](http://joss.theoj.org/papers/87c76a9d8f39f0dafbda6388b82f5cf0). _The Journal of Open Source Software_, **3**(22), 360, doi:10.21105/joss.00360.

    Hopkinson, R.F., D.W. McKenney, E.J. Milewska, M.F. Hutchinson, P. Papadopol, and L.A. Vincent, 2011: [Impact of Aligning Climatological Day on Gridding Daily Maximum–Minimum Temperature and Precipitation over Canada](http://journals.ametsoc.org/doi/abs/10.1175/2011JAMC2684.1)._ Journal of Applied Meteorology and Climatology_, **50**, 1654–1665. doi:10.1175/2011JAMC2684.1.

    Hunter, R. D., and R. K. Meentemeyer, 2005: [Climatologically Aided Mapping of Daily Precipitation and Temperature](http://journals.ametsoc.org/doi/abs/10.1175/JAM2295.1). _Journal of Applied Meteorology_, **44**, 1501–1510, doi:10.1175/JAM2295.1.

    Eum, H.-I., Dibike, Y., Prowse, T. and Bonsal, B., 2014, Inter-comparison of high-resolution gridded climate data sets and their implication on hydrological model simulation over the Athabasca Watershed, _Canada. Hydrol. Process._, **28**, 4250–4271. doi: 10.1002/hyp.10236.

    Li, C., Y. Fang, K. Calderia, X. Zhang, N.S. Diffenbaugh, and A.M. Michalak, 2018: [Widespread persistent changes to temperature extremes occurred earlier than predicted](https://www.nature.com/articles/s41598-018-19288-z). _Nature Scientific Reports_, **8**, 1007, doi:10.1038/s41598-018-19288-z  

    Maurer, E.P., and H.G. Hidalgo, 2008: [Utility of daily vs. monthly large-scale climate data: an intercomparison of two statistical downscaling methods](http://www.hydrol-earth-syst-sci.net/12/551/2008/hess-12-551-2008.html). _Hydrology and Earth System Sciences_, **12**, 2, 551-563. doi:10.5194/hess-12-551-2008.

    Maurer, E., H. Hidalgo, T. Das, M. Dettinger, and D. Cayan, 2010: [The utility of daily large-scale climate data in the assessment of climate change impacts on daily streamflow in California](http://www.hydrol-earth-syst-sci.net/14/1125/2010/hess-14-1125-2010.html). _Hydrology and Earth System Sciences_, **14**, 6, 1125–1138, doi:10.5194/hess-14-1125-2010.

    McKenney, D.W., M.F. Hutchinson, P. Papadopol, K. Lawrence, J. Pedlar, K. Campbell, E. Milewska, R. Hopkinson, D. Price, and T. Owen, 2011: [Customized spatial climate models for North America](http://journals.ametsoc.org/doi/abs/10.1175/2011BAMS3132.1). _Bulletin of the American Meteorological Society_, **92**, 12, 1611-1622. doi:10.1175/2011BAMS3132.1.

    Meinshausen, M., et al., 2011: The RCP greenhouse gas concentrations and their extensions from 1765 to 2300. _Climatic Change_, **109**(1-2), 213-241.

    **Sobie, S.R.**, and **T.Q. Murdock**, 2017: [High-Resolution Statistical Downscaling in Southwestern British Columbia](https://journals.ametsoc.org/doi/abs/10.1175/JAMC-D-16-0287.1)._ Journal of Applied Meteorology and Climatology_, **56**(6), 1625–1641, doi:10.1175/JAMC-D-16-0287.1.

    Taylor, K.E., R.J. Stouffer, and G.A. Meehl, 2012:[ An Overview of CMIP5 and the Experiment Design](http://journals.ametsoc.org/doi/abs/10.1175/BAMS-D-11-00094.1). _Bulletin of the American Meteorological Society_, **93**, 485–498. doi: 10.1175/BAMS-D-11-00094.1.

    **Werner, A.T.**, 2011: _[BCSD downscaled transient climate projections for eight select GCMs over British Columbia](http://www.pacificclimate.org/sites/default/files/publications/Werner.HydroModelling.FinalReport1.Apr2011.pdf), Canada_. Pacific Climate Impacts Consortium, University of Victoria, Victoria, BC, 63 pp.

    **Werner, A.T.** and **A.J. Cannon**, 2015: Hydrologic extremes – an intercomparison of multiple gridded statistical downscaling methods. _Hydrology and Earth System Sciences Discussion_, **12**, 6179-6239, doi:10.5194/hessd-12-6179-2015.

    Wood, A.W., L.R Leung, V. Sridhar, and D.P. Lettenmaier, 2004: [Hydrologic implications of dynamical and statistical approaches to downscaling climate model outputs](http://link.springer.com/article/10.1023%2FB%3ACLIM.0000013685.99609.9e). _Climatic Change_, **62**, 189–216, doi:10.1023/B:CLIM.0000013685.99609.9e.

