name: Climate Explorer Frontend CI

on: [push, pull_request]

jobs:
  node-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [9.x, 10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Node.js Test Suite
      run: |
        npm install 
        npm test
        
  docker-publish:
    needs: [node-test]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Get Branch
      uses: nelonoel/branch-name@v1
    - name: Get Tag
      uses: olegtarasov/get-tag@v2
    - name: Set env vars for build
      run: |
        echo ::set-env name=BRANCH::$(echo ${BRANCH_NAME})
        echo ::set-env name=TAG::$(echo ${GIT_TAG_NAME})
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pcic/climate-explorer-frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "${{ env.BRANCH }},${{ env.TAG }}"

  anchore:
    if: github.ref == 'refs/heads/master' || github.head_ref
    needs: [docker-publish]
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Branch Name
        uses: nelonoel/branch-name@v1
      - name: Set Branch Name to Environment Variable
        run: echo ::set-env name=TAG::$(echo ${BRANCH_NAME})
      - name: Scan Image
        uses: anchore/scan-action@master
        with:
          image-reference: "pcic/climate-explorer-frontend:${{ env.TAG }}"
